# Generated by Django 4.2.4 on 2023-09-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_remove_subject_grade_subject_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(default='teacher-email@industry.com', max_length=254, unique=True)),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
