# Generated by Django 4.2.4 on 2023-09-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='https://firebasestorage.googleapis.com/v0/b/fir-64ff1.appspot.com/o/user.png?alt=media&token=2d2e18cb-8019-4e0d-b215-1f4ed4b85ba9', max_length=True, upload_to='uploads/'),
        ),
    ]
