# Generated by Django 4.2.4 on 2023-09-14 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_attendance_student'),
        ('classroom', '0007_alter_teacher_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=5)),
                ('year', models.DateField()),
                ('created_at', models.DateField(auto_now=True)),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.grade')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.teacher')),
            ],
        ),
    ]
