# Generated by Django 4.2.4 on 2023-09-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_attendance_student'),
        ('classroom', '0008_classroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classroom',
            new_name='ClassroomModel',
        ),
    ]
